####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CXXFLAGS = -g -O2 -Wall -D_XSOCK_USE_SSL -I./src
LIBS = -lpthread -lssl -lcrypto
NAME = libcxxutils.a
ODIR = obj
OBJ = o

OBJS = xhttp.$(OBJ) \
	xsha256.$(OBJ) \
	xsock.$(OBJ) \
	xssl.$(OBJ) \
	xevent.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
INSTALL_INC = /usr/include/cxxutils
INSTALL_BIN = /usr/lib
VPATH = ./src

.cpp.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CXX) $(CXXFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(AR) rcs -o $(ODIR)/$(NAME) $(OBJECTS)

.PHONY: install
install:
	@test -d $(INSTALL_BIN) || mkdir -p $(INSTALL_BIN)
	@install -m 0755 $(ODIR)/$(NAME) $(INSTALL_BIN)/
	@test -d $(INSTALL_INC) || mkdir -p $(INSTALL_INC)
	@cp -r $(VPATH)/*.h $(INSTALL_INC)/

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
